[icon]
prepend_dirs = [
  { name = "Development", text = "" },
  { name = "Notes", text = "" },

  { name = "cmd", text = "" },
  { name = "internal", text = "" },
  { name = "assets", text = "" },
  { name = "bin", text = "" },
  { name = "Github", text = "" },
  { name = "Books", text = "󱉟" },
  { name = "Coding", text = "" },
  { name = "Golang", text = "" },
  { name = "archive", text = "" },
  { name = "CLI", text = "" },
  { name = "Web", text = "󰖟" },
  { name = "DevOps", text = "" },
]
