[opener]
extract = [{ run = 'ouch d -y "$@"', desc = "Extract here with ouch" }]
play = [{ run = 'mpv "$@"', orphan = true }]
edit = [{ run = '$EDITOR "$@"', block = true }]
open = [{ run = 'xdg-open "$@"', orphan = true, desc = "Open" }]

[plugin]
prepend_previewers = [
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { name = "*.md", run = "glow" },
  { name = "*/", run = "eza-preview" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[manager]
linemode = "size_and_mtime"

[[opener.add-sub]]
run = ''' echo sub-add "'$0'" | socat - /tmp/mpv.sock '''
desc = "Add sub to MPV"
[[open.prepend_rules]]
name = "*.{ass,srt,ssa,sty,sup,vtt}"
use = ["add-sub", "edit"]
